### ISSUE TITLE
[Bug] OSC data are sent to a random UDP port and not the assigned SendPort in the vars.json

### ISSUE THREAD

**Issue by Nyabloody** [Sergey004/Quest2-VRC#33]
**Describe the bug**
The software seems to be running but is sending OSC data to a random UDP port and not the assigned SendPort, leading to VRChat not receiving any OSC data at all from the software.

**To Reproduce**
Set SendPort to 9000 in vars.json
Launch software and tick "Link or AirLink (Or VD)" toggle to connect the software to the headset wirelessly
Click on "SEND ONLY" button to start sending OSC data to VRChat
Logs show "OSC UDP port is xxxxx" where xxxxx is a random port everytime

**Expected behavior**
Make the software actually send OSC data to the set SendPort in vars.json and not a random port.

**Screenshots**
![2025-01-07_15-34-13](https://github.com/user-attachments/assets/084738c8-ae7a-424e-9a24-ed50dc9ca79b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Quest OS Version: v72
 - Unity ver: 2022.3.22f1

**Additional context**
Also not being able to see the text in the dialog boxes doesn't help either to understand what each buttons does, see my other issue.

**Comment by Sergey004** [comment]
fixed in 28d6db00bc4fd5f2f2a36e87e3d70c0ac88f1128

The last commit includes also fixes for empty dialog windows

**Comment by Nyabloody** [comment]
Ok so dialog boxes are indeed fixed but OSC messages are still not being sent to vrchat. Is it possible to have a build without OSCQuery? It always caused issues for me, I prefer the old way using a different port for each apps and route everything with VRCOSC.

**Comment by Sergey004** [comment]
Okay, I'll try to make OSCQuery completely disabled, via the settings file
